//! Plugin crate skeleton.
//!
//! This repo was generated by the meta-workspace harness.
//! Keep this crate thin: plugin-specific DSP/params/state + declarative UI composition only.

#![warn(missing_docs)]
#![warn(rustdoc::missing_crate_level_docs)]

/// Temporary placeholder so the crate has a public surface.
pub fn placeholder() {}

pub mod gui;
